### ISSUE TITLE
Add keep values.yaml files option

### ISSUE THREAD

**Issue by 1ethanhansen** [mtarsel/ContainerAnalysis#13]
To reduce run time for testing, add option to use local values.yaml files and skip process of pulling them from the interwebs

**Comment by mtarsel** [comment]
This is a great idea. One thing I will mention is the Charts.yaml is not saved in the Applications/ dir and I think that should be addressed with this issue. The Applications/ should contain the values.yaml and Chart.yaml in the app's directory. 

The code should still pull the latest application's zip files if the Applications/ directory does not exist. If Applications/ exist, use app's Charts.yaml and values.yaml - this should reduce run time greatly 😃

**Comment by 1ethanhansen** [comment]
I'm working on this currently, however rather than detecting automatically if Applications/ exists I'm making it a command line option (-k or --keep). Also i'm not sure this will in fact reduce the runtime substantially. it appears the majority of the time spent in the parse_index stage is spend parsing yaml files, not downloading and extracting them. I'll run a couple tests to be sure, but from what I'm seeing right now it will reduce the runtime by less than 30 seconds.

**Comment by 1ethanhansen** [comment]
w/o --keep runtime: 12:25.377745
w/  --keep runtime: 11:37.530429

In other words: I was wrong

**Comment by mtarsel** [comment]
70151da2dde95a
