### ISSUE TITLE
Make program flow stage-based

### ISSUE THREAD

**Issue by 1ethanhansen** [mtarsel/ContainerAnalysis#20]
Currently there are a lot of nested for loop that could be turned each into an individual stage, for instance, to get, extract, and parse the values.yaml the deepest (sorta) stack trace looks like this:
```
(get-image-info.py) main -> parse_index_yaml -> (indexparser.py) get_tarfile -> obtain_values_yaml -> get_app_info -> parse-image_repo
```
and the flow currently looks like this:
```
for main_image:
  download, open, extract tarfile
  for item in tarfile:
    if (values.yaml):
      find images, tags, repos in values.yaml
      for each potential_repo:
        if potential_repo is dict:
          for item in dict:
            if item is dict:
              for sub_item in item:
                if correct_format:
                  append(sub_item) to app_obj
      for repos in app_obj:
        clean the repos
```
I think that could be cleaned up considerably if you did some thing like
```
# Stage1: download and extract
for each main_image:
  download, open, extract tarfile
# stage2: find values.yaml
for each main_image:
  find values.yaml
  find find images, tags, repos in values.yaml
# stage3: get potential repos
for each potential_repo:
  if potential_repo is dict:
    for item in dict:
      if item is dict:
        for sub_item in item:
          if correct_format:
            append(sub_item) to app_obj
# stage4: clean the repos
```

this is a bigger undertaking and might take a while, but this way the code is more modular and easier to read, with fewer traces of "what calls what calls what?"

**Comment by mtarsel** [comment]
Yes, there needs to be a re-haul to fix the "what calls what" problem. Lets discuss this first before doing anything.

**Comment by 1ethanhansen** [comment]
> Yes, there needs to be a re-haul to fix the "what calls what" problem. Lets discuss this first before doing anything.

Sounds good to me

**Comment by mtarsel** [comment]
Obtain, Parse, Download

**Stage 1: Initialize Main Image**
	Given a index.yaml, parse Application name.
	Initialize App object (name, base_url)
	App’s name will be used to send request to GitHub api
	base_url is taken from the tarball link in index.yaml. Url is split and re-constructed to just add +values or +Chart to get raw files.
Raw url = https://raw.githubusercontent.com/IBM/charts/master/stable/ibm-wmlce-dev/Chart.yaml
Url in yaml =  https://raw.githubusercontent.com/IBM/charts/master/repo/stable/ibm-wmlce-dev-2.0.2.tgz

Note the repo/stable difference.

**Stage 2: Get Product Name**

**Stage 3: Obtain keywords** 
	Parse index.yaml to get keywords
	Use Github API to download raw Chart.yaml in —debug
See #22 


**Stage 4: Download raw values.yaml**
	Added to Applications/{app_name}/

**Stage 5: Initialize Image Object**
	Get repos, Images, tags - the real bulk of the program.

**Stage 6: Output to CSV**

**Comment by mtarsel** [comment]
Stage 5 could be split up a lot more but I think this is a good overview for now.

**Comment by 1ethanhansen** [comment]
I _really_ like the idea of making the majority of the first few stages methods of objects.
so here's some pseudocode:

* get hub list and github token
* get index location #either local or remote
* app_list = parse index.yaml #init each app w/ name, url, and keywords from index.yaml
* for app in app_list: #app initialization stage
  * app.get_values_yaml() #just downloads the values.yaml file
  * app.get_chart_yaml() #just downloads the chart.yaml file
  * app.parse_values_yaml() #populates fields in app
  * app.clean_repos()
  * app.get_product_name()
  * app.repo_crawl() #not much to change here from runit()
  * app.output_to_csv() #In this overhaul I'm also going to overhaul how it is the csv file is generated

Is there anything I missed?

**Comment by mtarsel** [comment]
I prefer we get the keywords and product names first and then for the rest of execution we only deal with values.yaml.

Similar idea but I cleaned it up:

* get hub list and github token
* get index location #either local or remote
* app_list = parse index.yaml # Initialize Applications(name, url, keywords) from index.yaml
* for app in app_list: #populate App objects
  * app.get_product_name()
  * if debug: app.get_chart_yaml() #just downloads the chart.yaml file
  * app.get_values_yaml() #just downloads the values.yaml file
  * app.parse_values_yaml() #populates fields in app
  * app.clean_repos()
  * app.repo_crawl() #not much to change here from runit()
  * app.output_to_csv() #In this overhaul I'm also going to overhaul how it is the csv file is generated

**Comment by 1ethanhansen** [comment]
Forgot a few steps

* get hub list and github token
* get index location #either local or remote
* app_list = parse index.yaml # Initialize Applications(name, url, keywords) from index.yaml
* setup outputs()
* for app in app_list: #populate App objects  
  * app.get_product_name()
  * if debug: app.get_chart_yaml() #just downloads the chart.yaml file
  * app.get_values_yaml() #just downloads the values.yaml file
  * app.parse_values_yaml() #populates fields in app
  * app.clean_repos()
  * app.repo_crawl() #not much to change here from runit()
  * app.output_to_csv() #In this overhaul I'm also going to overhaul how it is the csv file is generated
