### ISSUE TITLE
Add runtime to progress bar and log messages

### ISSUE THREAD

**Issue by 1ethanhansen** [mtarsel/ContainerAnalysis#21]
progress bar: [###    ] %done TIME
logs: ------TIME------

**Comment by mtarsel** [comment]
I've seen the addition of the progress bar and the runtime was added here: e9c8fe8cb3aa10b5a047

I don't think logging this would be that helpful since the big re-haul makes the code much more readable.

**Comment by 1ethanhansen** [comment]
I was saying add the runtime to the progress bar so we can see how long its been going for in real time, and the runtime isn't currently logged to a file anywhere. Neither is the progress after the rehaul.
