### ISSUE TITLE
PEP8 Enablement including Comments

### ISSUE THREAD

**Issue by 1ethanhansen** [mtarsel/ContainerAnalysis#27]
Make everything PEP8 and increase in-code documentation (comments)

**Comment by mtarsel** [comment]
https://www.python.org/dev/peps/pep-0008/

**Comment by 1ethanhansen** [comment]
Includes finding unused imports, variables, functions, code in general

**Comment by 1ethanhansen** [comment]
potentially unused:

* num-supported_images edit
* also sub_images_supported
* values_exists
* Chart_exists

**Comment by ryescholin** [comment]
Imma work on this one...
