### ISSUE TITLE
Add travis badge to README

### ISSUE THREAD

**Issue by 1ethanhansen** [mtarsel/ContainerAnalysis#3]
[ENHANCEMENT]

Since everything in the code is ready for Travis CI integration (on a basic level), there should be a Travis Badge in the README. That requires @mtarsel to link his github to Travis CI first, then we can get the markdown with a link to the travis badge image

related to #2

**Comment by mtarsel** [comment]
Travis CI should now be linked to this repo.

**Comment by 1ethanhansen** [comment]
[![Build Status](https://travis-ci.com/mtarsel/ContainerAnalysis.svg?branch=master)](https://travis-ci.com/mtarsel/ContainerAnalysis)

testing if it works
