### ISSUE TITLE
Create way to save docker info locally

### ISSUE THREAD

**Issue by 1ethanhansen** [mtarsel/ContainerAnalysis#31]
Since the majority of the runtime comes from crawling dockerhub, what if we were able to just save all of the information we pulled from dockerhub locally? A couple ideas to do this:

* Save the information we pull as json files, since it come in json format already
* save all of the information we have on apps as json files (so we don't need to pull anything, no values.yaml, no README.md, no Chart.yaml)

This should reduce the runtime even further than #13 did

**Comment by mtarsel** [comment]
In debug mode there was a file created called generated_input.yaml that had this info - this would be a good start since this code already exists (somewhere). I'm not opposed to json

**Comment by 1ethanhansen** [comment]
The reason I'm most likely going to use json is it is super easy to just dump an object into json and then read it back, but from what I can see there's a bit more finagling required to do the same with a yaml file

**Comment by 1ethanhansen** [comment]
> The reason I'm most likely going to use json is it is super easy to just dump an object into json and then read it back, but from what I can see there's a bit more finagling required to do the same with a yaml file

After looking into it a bit more it appears that while saving an app to a json object will be slightly easier, loading from a json object into an app will be far more difficult than parsing yaml. Therefore I'll go with the yaml for now

**Comment by 1ethanhansen** [comment]
I am going to work on #37 before this one
