### ISSUE TITLE
Add Progress bar to project

### ISSUE THREAD

**Issue by 1ethanhansen** [mtarsel/ContainerAnalysis#4]
[ENHANCEMENT]

Currently there is no way to see how long the application has been running for or how close it is to finishing. A simple progress bar would do that

**Comment by mtarsel** [comment]
This is a great idea to give some feedback about what is being executed. I'd also recommend adding log messages that align with the progress bar status. Adding more logging in these areas of the code will provide some 'checkpoints' in the log file that may help for debugging in the future.

**Comment by 1ethanhansen** [comment]
Fixed in 64b43241b9b91edb852a27099e2f0ed045c44ca1
