### ISSUE TITLE
Share results from program output

### ISSUE THREAD

**Issue by mtarsel** [mtarsel/ContainerAnalysis#41]
Since #40 is going to stay "private", imo the best way to share the results would be to:

* Execute get-image-info.py on a Jenkins server
* Cross-validate (#40), get results, get diff (#39)
* Share info via Slack API from Jenkins

When there is a diff or something is very wrong, this should be shared in our slack channel.

So this issue depends on #39 and #40 being closed first.

**Comment by mtarsel** [comment]
what's the status of this issue?

**Comment by ryescholin** [comment]
4/5 done, I went down some weird rabbit hole for way longer than i wish i had, sorry
