### ISSUE TITLE
Support other Docker repos

### ISSUE THREAD

**Issue by 1ethanhansen** [mtarsel/ContainerAnalysis#8]
Not just dockerhub.com

from [The wiki](https://github.com/mtarsel/ContainerAnalysis/wiki)

**Comment by 1ethanhansen** [comment]
focusing on Si's requests first

**Comment by 1ethanhansen** [comment]
@mtarsel did this mean repos or registries? In other words are we looking to add more support for apps' repos that currently come up with "Image is bad" or "Not found in repo", or are we looking to add support so that other websites can be crawled as well, like https://quay.io/ ?

**Comment by mtarsel** [comment]
lets focus on the "Image is bad" and the "Not found in repo" problems first before enabling different repositories. I think there was around 13 "bad apps" that need to be addressed.

**Comment by 1ethanhansen** [comment]
Will do!

**Comment by 1ethanhansen** [comment]
Increasing urgency because as I'm going through this issue I am also finding that some "supported" docker repos aren't giving the correct outputs to results.csv
